model:
  internvl_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/ckpt/OpenGVLab/InternVL3_5-4B
  quantizer:
    type: MLP # [MLP, ViT]
    input_feature_dim: 4096
    output_dim: 16
    llm_hidden_size: 2560

train:
  root: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/experiment
  resume_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/experiment/vq_llava_distill/1128_lfq_mlp_16_intern4B_desdata/quantizer-vq_llava_distill-50000
  global_step: 50001

  exp_name: &exp_name vq_llava_distill
  proj_name: *exp_name
  output_dir: 1128_lfq_mlp_16_intern4B_desdata
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: swanlab

  lr: 1e-4
  num_iter: 100000
  save_every: 2000

data:
  img_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/dataset/llava665k
  ann_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/dataset/liuhaotian/LLaVA-Instruct-150K/llava_v1_5_mix665k.json
  des_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/dataset/liuhaotian/LLaVA-Instruct-150K/output.json
  batch_size: 18
  num_workers: 8
  max_seq_length: 640
  num_image_token: 256