model:
  internvl_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/ckpt/OpenGVLab/InternVL3_5-8B
  quantizer:
    type: MLP # [MLP, ViT]
    input_feature_dim: 4096
    output_dim: 16
    llm_hidden_size: 4096

train:
  root: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/experiment
  resume_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/experiment/vq_llava_distill/1202_mlp_16_8B/quantizer-vq_llava_distill-28000
  global_step: 28001

  exp_name: &exp_name vq_llava_distill
  proj_name: *exp_name
  output_dir: 1202_mlp_16_8B
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: swanlab

  lr: 1e-4
  num_iter: 100000
  save_every: 2000
  hp_mse: 0.0
  hp_cosine: 0.0

data:
  img_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/dataset/llava665k
  ann_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/dataset/liuhaotian/LLaVA-Instruct-150K/llava_v1_5_mix665k.json
  des_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/dataset/liuhaotian/LLaVA-Instruct-150K/output.json
  batch_size: 12
  num_workers: 8
  max_seq_length: 640
  num_image_token: 256