model:
  internvl_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/ckpt/OpenGVLab/InternVL3_5-1B
  quantizer:
    output_dim: 14
    llm_hidden_size: 1024
    ckpt_path: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/ckpt/LlamaGen/vq_ds16_t2i.pt

train:
  root: /inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/experiment
  resume_path: null
  skip_keys: []
  global_step: 0

  exp_name: &exp_name llamagen
  proj_name: *exp_name
  output_dir: 1126_intern1B_384
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: swanlab

  lr: 1e-4
  num_iter: 1000000
  save_every: 2000

data:
  wds_path: [/inspire/ssd/project/advanced-machine-learning-and-deep-learning-applications/yangyi-253108120173/ssd/jjc/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption]
  img_size: 384
  cfg_drop_rate: 0.1
  num_img_token: 576
  max_seq_length: 640
  buffer_size: 5000
  batch_size: 80
  num_workers: 8